blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://krakennet.github.io/fathom
    about: Check the docs before opening an issue
  - name: Discussions
    url: https://github.com/KrakenNet/fathom/discussions
    about: Ask questions and discuss ideas
