blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.gg/E6Cf8WFDf
    about: Chat with the community and ask questions.
  - name: Documentation
    url: https://krakennet.github.io/fathom
    about: Check the docs before opening an issue
  - name: Discussions
    url: https://github.com/KrakenNet/fathom/discussions
    about: Ask questions and discuss ideas
