import shutil
import subprocess
import sys
from pathlib import Path

import pytest


def test_go_sdk_docs_generated(tmp_path: Path) -> None:
    if shutil.which("go") is None:
        pytest.skip("go not available")
    out = tmp_path / "go-sdk"
    result = subprocess.run(
        [sys.executable, "scripts/generate_go_sdk_docs.py", str(out)],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    md = (out / "fathom-go.md").read_text(encoding="utf-8")
    # The gomarkdoc header proves the tool actually ran.
    assert md.startswith("<!-- Code generated by gomarkdoc")


def test_go_sdk_docs_are_deterministic(tmp_path: Path) -> None:
    if shutil.which("go") is None:
        pytest.skip("go not available")
    out_a = tmp_path / "a"
    out_b = tmp_path / "b"
    for out in (out_a, out_b):
        result = subprocess.run(
            [sys.executable, "scripts/generate_go_sdk_docs.py", str(out)],
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 0, result.stderr

    regenerated = (out_a / "fathom-go.md").read_bytes()
    assert regenerated == (out_b / "fathom-go.md").read_bytes(), (
        "gomarkdoc output differs between regens — flag version or input drift"
    )

    # The "regenerated == committed" gate that used to live here was
    # removed in favour of the canonical drift gate in
    # ``.github/workflows/docs.yml`` (``Drift gate`` step), which runs
    # ``make docs-gen && make docs-gen-foreign`` against a pinned Go +
    # gomarkdoc + Node + pnpm toolchain. This unit test ran against
    # whatever Go the runner happened to ship (Go 1.24 on ubuntu-latest,
    # different on macOS / Windows) and broke every PR whenever the
    # committer's Go version diverged from the runner's by even a single
    # minor — gomarkdoc's link-rendering output is not byte-stable across
    # Go releases. Keep the determinism guarantee; drop the cross-machine
    # comparison.
