import shutil
import subprocess
import sys
from pathlib import Path

import pytest


def test_go_sdk_docs_generated(tmp_path: Path) -> None:
    if shutil.which("go") is None:
        pytest.skip("go not available")
    out = tmp_path / "go-sdk"
    result = subprocess.run(
        [sys.executable, "scripts/generate_go_sdk_docs.py", str(out)],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    md = (out / "fathom-go.md").read_text(encoding="utf-8")
    # The gomarkdoc header proves the tool actually ran.
    assert md.startswith("<!-- Code generated by gomarkdoc")


def test_go_sdk_docs_are_deterministic(tmp_path: Path) -> None:
    if shutil.which("go") is None:
        pytest.skip("go not available")
    out_a = tmp_path / "a"
    out_b = tmp_path / "b"
    for out in (out_a, out_b):
        result = subprocess.run(
            [sys.executable, "scripts/generate_go_sdk_docs.py", str(out)],
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 0, result.stderr

    regenerated = (out_a / "fathom-go.md").read_bytes()
    assert regenerated == (out_b / "fathom-go.md").read_bytes(), (
        "gomarkdoc output differs between regens — flag version or input drift"
    )

    # Drift vs the committed docs/reference/go-sdk/fathom-go.md is enforced by
    # the docs workflow's drift gate (`make docs-gen-foreign` + `git diff
    # --exit-code`), which runs in an environment with full git history and
    # the pinned Go toolchain. It is intentionally not asserted here: this
    # job runs in the regular CI lane where the GitHub-runner checkout is
    # shallow, which causes gomarkdoc to omit the source-URL anchors that
    # the committed copy contains.
