"""Regenerate SSVC rule pack branches + rules from the pinned decision-table CSVs.

Reads the sha256-pinned CSVs under
``src/fathom/rule_packs/ssvc/references/csv/`` and deterministically emits,
for each of the three decision trees (supplier, deployer, CISA):

- ``references/branches-<tree>.yaml`` — the enumerated branch list
- ``rules/ssvc_<tree>_rules.yaml`` — one fathom rule per branch

Run from the repository root after replacing a reference CSV (see the
version-bump rule in ``src/fathom/rule_packs/ssvc/README.md``):

    uv run python scripts/generate_ssvc_rules.py

Output is byte-stable for unchanged inputs; CI tests compare the committed
YAML against the CSVs, so this script and the pack must land together.
"""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Any

import yaml

PACK_DIR = Path("src/fathom/rule_packs/ssvc")
CSV_DIR = PACK_DIR / "references" / "csv"

# CSV cell value -> CLIPS symbol used in templates/rules.
# Decision-point *names* are mapped per tree in TREES below.
VALUE_MAP = {
    "public poc": "poc",  # Exploitation v1.1.0 renamed the middle value; the
    # CISA guide (Table 9) and this pack keep the short form.
    "super effective": "super_effective",
    "very high": "very_high",
}

# CISA publishes capitalized decision labels (guide Table 9); the CERTCC CSV
# carries them lowercase.
CISA_LABEL_MAP = {
    "track": "Track",
    "track*": "Track*",
    "attend": "Attend",
    "act": "Act",
}

TREES: list[dict[str, Any]] = [
    {
        "tree": "supplier",
        "module": "ssvc_supplier",
        "ruleset": "ssvc-supplier-tree",
        "version": "1.0.0",
        "csv": "supplier_patch_development_priority_1_0_0.csv",
        "title": "CERT/CC SSVC Supplier patch-development priority tree",
        "source": ("CERTCC/SSVC data/csv/ssvc/supplier_patch_development_priority_1_0_0.csv"),
        "columns": [
            ("Exploitation v1.1.0", "exploitation"),
            ("Utility v1.0.1", "utility"),
            ("Technical Impact v1.0.0", "technical_impact"),
            ("Public Safety Impact v2.0.1", "public_safety_impact"),
        ],
        "outcome": "Defer, Scheduled, Out-of-Cycle, Immediate v1.0.0",
        "label_map": {},
    },
    {
        "tree": "deployer",
        "module": "ssvc_deployer",
        "ruleset": "ssvc-deployer-tree",
        "version": "1.0.0",
        "csv": "deployer_patch_application_priority_1_0_0.csv",
        "title": "CERT/CC SSVC Deployer patch-application priority tree",
        "source": ("CERTCC/SSVC data/csv/ssvc/deployer_patch_application_priority_1_0_0.csv"),
        "columns": [
            ("Exploitation v1.1.0", "exploitation"),
            ("System Exposure v1.0.1", "exposure"),
            ("Automatable v2.0.0", "automatable"),
            ("Human Impact v2.0.2", "human_impact"),
        ],
        "outcome": "Defer, Scheduled, Out-of-Cycle, Immediate v1.0.0",
        "label_map": {},
    },
    {
        "tree": "cisa",
        "module": "ssvc_cisa",
        "ruleset": "ssvc-cisa-tree",
        "version": "2.0.3",
        "csv": "cisa_coordinator_2_0_3.csv",
        "title": "CISA SSVC v2.0.3 vulnerability triage tree",
        "source": (
            "CISA SSVC Guide (Table 9, p.10); cross-checked against "
            "CERTCC/SSVC data/csv/cisa/cisa_coordinator_2_0_3.csv"
        ),
        "columns": [
            ("Exploitation v1.1.0", "exploitation"),
            ("Automatable v2.0.0", "automatable"),
            ("Technical Impact v1.0.0", "technical_impact"),
            ("Mission and Well-Being Impact v1.0.0", "mission_wellbeing"),
        ],
        "outcome": "CISA Levels v1.1.0 (cisa)",
        "label_map": CISA_LABEL_MAP,
    },
]


def _sym(value: str) -> str:
    """Map a CSV cell value to its CLIPS symbol."""
    return VALUE_MAP.get(value, value.replace(" ", "_"))


def load_branches(spec: dict[str, Any]) -> list[dict[str, str]]:
    """Read one decision-table CSV into ordered branch dicts."""
    branches: list[dict[str, str]] = []
    with open(CSV_DIR / spec["csv"], newline="") as f:
        for row in csv.DictReader(f):
            branch = {slot: _sym(row[col]) for col, slot in spec["columns"]}
            label = row[spec["outcome"]]
            branch["decision"] = spec["label_map"].get(label, label)
            branches.append(branch)
    return branches


def _header(spec: dict[str, Any], kind: str) -> str:
    lines = [
        f"# {spec['title']} — {kind}.",
        "#",
        f"# GENERATED by scripts/generate_ssvc_rules.py from references/csv/{spec['csv']}",
        "# (sha256-pinned in references/SHA256SUMS). Do not edit by hand —",
        "# regenerate per the version-bump rule in the pack README.",
        "#",
        f"# Source: {spec['source']}",
        "# Decision-point CSV values map to CLIPS symbols via:",
        '#   "public poc" -> poc, "super effective" -> super_effective,',
        '#   "very high" -> very_high (spaces become underscores).',
        "",
    ]
    return "\n".join(lines)


def write_branches(spec: dict[str, Any], branches: list[dict[str, str]]) -> None:
    path = PACK_DIR / "references" / f"branches-{spec['tree']}.yaml"
    body = yaml.safe_dump(branches, sort_keys=False, default_flow_style=False)
    path.write_text(_header(spec, f"all {len(branches)} published branches") + body)
    print(f"wrote {path} ({len(branches)} branches)")


def write_rules(spec: dict[str, Any], branches: list[dict[str, str]]) -> None:
    rules = []
    for i, branch in enumerate(branches, 1):
        conditions = [
            {
                "template": slot,
                "conditions": [{"slot": "value", "expression": f"equals({branch[slot]})"}],
            }
            for _, slot in spec["columns"]
        ]
        rules.append(
            {
                "name": f"ssvc_{spec['tree']}_{i:02d}",
                "salience": 10,
                "when": conditions,
                "then": {
                    "action": "route",
                    "reason": f"SSVC {spec['tree']} decision: {branch['decision']}",
                    "metadata": {"decision": branch["decision"]},
                },
            }
        )
    doc = {
        "module": spec["module"],
        "ruleset": spec["ruleset"],
        "version": spec["version"],
        "rules": rules,
    }
    path = PACK_DIR / "rules" / f"ssvc_{spec['tree']}_rules.yaml"
    body = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)
    path.write_text(_header(spec, f"one rule per branch ({len(rules)} rules)") + body)
    print(f"wrote {path} ({len(rules)} rules)")


def main() -> None:
    for spec in TREES:
        branches = load_branches(spec)
        write_branches(spec, branches)
        write_rules(spec, branches)


if __name__ == "__main__":
    main()
