# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import fathom_pb2 as fathom__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fathom_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FathomServiceStub(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Evaluate = channel.unary_unary(
                '/fathom.v1.FathomService/Evaluate',
                request_serializer=fathom__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=fathom__pb2.EvaluateResponse.FromString,
                _registered_method=True)
        self.AssertFact = channel.unary_unary(
                '/fathom.v1.FathomService/AssertFact',
                request_serializer=fathom__pb2.AssertFactRequest.SerializeToString,
                response_deserializer=fathom__pb2.AssertFactResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/fathom.v1.FathomService/Query',
                request_serializer=fathom__pb2.QueryRequest.SerializeToString,
                response_deserializer=fathom__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Retract = channel.unary_unary(
                '/fathom.v1.FathomService/Retract',
                request_serializer=fathom__pb2.RetractRequest.SerializeToString,
                response_deserializer=fathom__pb2.RetractResponse.FromString,
                _registered_method=True)
        self.SubscribeChanges = channel.unary_stream(
                '/fathom.v1.FathomService/SubscribeChanges',
                request_serializer=fathom__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=fathom__pb2.FactChange.FromString,
                _registered_method=True)
        self.Reload = channel.unary_unary(
                '/fathom.v1.FathomService/Reload',
                request_serializer=fathom__pb2.ReloadRequest.SerializeToString,
                response_deserializer=fathom__pb2.ReloadResponse.FromString,
                _registered_method=True)


class FathomServiceServicer(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def Evaluate(self, request, context):
        """Evaluate asserted facts against loaded rules and return a decision.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssertFact(self, request, context):
        """Assert one or more facts into working memory.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Query working memory for facts matching a template and optional filter.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retract(self, request, context):
        """Retract facts matching a template and optional filter.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeChanges(self, request, context):
        """Stream working-memory changes as they occur during evaluation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reload(self, request, context):
        """Hot-reload the ruleset from a path or inline YAML.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FathomServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=fathom__pb2.EvaluateRequest.FromString,
                    response_serializer=fathom__pb2.EvaluateResponse.SerializeToString,
            ),
            'AssertFact': grpc.unary_unary_rpc_method_handler(
                    servicer.AssertFact,
                    request_deserializer=fathom__pb2.AssertFactRequest.FromString,
                    response_serializer=fathom__pb2.AssertFactResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=fathom__pb2.QueryRequest.FromString,
                    response_serializer=fathom__pb2.QueryResponse.SerializeToString,
            ),
            'Retract': grpc.unary_unary_rpc_method_handler(
                    servicer.Retract,
                    request_deserializer=fathom__pb2.RetractRequest.FromString,
                    response_serializer=fathom__pb2.RetractResponse.SerializeToString,
            ),
            'SubscribeChanges': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeChanges,
                    request_deserializer=fathom__pb2.SubscribeRequest.FromString,
                    response_serializer=fathom__pb2.FactChange.SerializeToString,
            ),
            'Reload': grpc.unary_unary_rpc_method_handler(
                    servicer.Reload,
                    request_deserializer=fathom__pb2.ReloadRequest.FromString,
                    response_serializer=fathom__pb2.ReloadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fathom.v1.FathomService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fathom.v1.FathomService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FathomService(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fathom.v1.FathomService/Evaluate',
            fathom__pb2.EvaluateRequest.SerializeToString,
            fathom__pb2.EvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssertFact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fathom.v1.FathomService/AssertFact',
            fathom__pb2.AssertFactRequest.SerializeToString,
            fathom__pb2.AssertFactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fathom.v1.FathomService/Query',
            fathom__pb2.QueryRequest.SerializeToString,
            fathom__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fathom.v1.FathomService/Retract',
            fathom__pb2.RetractRequest.SerializeToString,
            fathom__pb2.RetractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fathom.v1.FathomService/SubscribeChanges',
            fathom__pb2.SubscribeRequest.SerializeToString,
            fathom__pb2.FactChange.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fathom.v1.FathomService/Reload',
            fathom__pb2.ReloadRequest.SerializeToString,
            fathom__pb2.ReloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
