// Fathom gRPC service definition.
//
// Provides remote access to the Fathom deterministic reasoning engine
// for evaluating policy rules, managing working memory, and streaming
// fact changes.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: fathom.proto

package fathomv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FathomService_Evaluate_FullMethodName         = "/fathom.v1.FathomService/Evaluate"
	FathomService_AssertFact_FullMethodName       = "/fathom.v1.FathomService/AssertFact"
	FathomService_Query_FullMethodName            = "/fathom.v1.FathomService/Query"
	FathomService_Retract_FullMethodName          = "/fathom.v1.FathomService/Retract"
	FathomService_SubscribeChanges_FullMethodName = "/fathom.v1.FathomService/SubscribeChanges"
	FathomService_Reload_FullMethodName           = "/fathom.v1.FathomService/Reload"
)

// FathomServiceClient is the client API for FathomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FathomServiceClient interface {
	// Evaluate asserted facts against loaded rules and return a decision.
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error)
	// Assert one or more facts into working memory.
	AssertFact(ctx context.Context, in *AssertFactRequest, opts ...grpc.CallOption) (*AssertFactResponse, error)
	// Query working memory for facts matching a template and optional filter.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Retract facts matching a template and optional filter.
	Retract(ctx context.Context, in *RetractRequest, opts ...grpc.CallOption) (*RetractResponse, error)
	// Stream working-memory changes as they occur during evaluation.
	SubscribeChanges(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FactChange], error)
	// Hot-reload the ruleset from a path or inline YAML.
	Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error)
}

type fathomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFathomServiceClient(cc grpc.ClientConnInterface) FathomServiceClient {
	return &fathomServiceClient{cc}
}

func (c *fathomServiceClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateResponse)
	err := c.cc.Invoke(ctx, FathomService_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fathomServiceClient) AssertFact(ctx context.Context, in *AssertFactRequest, opts ...grpc.CallOption) (*AssertFactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssertFactResponse)
	err := c.cc.Invoke(ctx, FathomService_AssertFact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fathomServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, FathomService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fathomServiceClient) Retract(ctx context.Context, in *RetractRequest, opts ...grpc.CallOption) (*RetractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetractResponse)
	err := c.cc.Invoke(ctx, FathomService_Retract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fathomServiceClient) SubscribeChanges(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FactChange], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FathomService_ServiceDesc.Streams[0], FathomService_SubscribeChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, FactChange]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FathomService_SubscribeChangesClient = grpc.ServerStreamingClient[FactChange]

func (c *fathomServiceClient) Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadResponse)
	err := c.cc.Invoke(ctx, FathomService_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FathomServiceServer is the server API for FathomService service.
// All implementations must embed UnimplementedFathomServiceServer
// for forward compatibility.
type FathomServiceServer interface {
	// Evaluate asserted facts against loaded rules and return a decision.
	Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error)
	// Assert one or more facts into working memory.
	AssertFact(context.Context, *AssertFactRequest) (*AssertFactResponse, error)
	// Query working memory for facts matching a template and optional filter.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// Retract facts matching a template and optional filter.
	Retract(context.Context, *RetractRequest) (*RetractResponse, error)
	// Stream working-memory changes as they occur during evaluation.
	SubscribeChanges(*SubscribeRequest, grpc.ServerStreamingServer[FactChange]) error
	// Hot-reload the ruleset from a path or inline YAML.
	Reload(context.Context, *ReloadRequest) (*ReloadResponse, error)
	mustEmbedUnimplementedFathomServiceServer()
}

// UnimplementedFathomServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFathomServiceServer struct{}

func (UnimplementedFathomServiceServer) Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedFathomServiceServer) AssertFact(context.Context, *AssertFactRequest) (*AssertFactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssertFact not implemented")
}
func (UnimplementedFathomServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedFathomServiceServer) Retract(context.Context, *RetractRequest) (*RetractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Retract not implemented")
}
func (UnimplementedFathomServiceServer) SubscribeChanges(*SubscribeRequest, grpc.ServerStreamingServer[FactChange]) error {
	return status.Error(codes.Unimplemented, "method SubscribeChanges not implemented")
}
func (UnimplementedFathomServiceServer) Reload(context.Context, *ReloadRequest) (*ReloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedFathomServiceServer) mustEmbedUnimplementedFathomServiceServer() {}
func (UnimplementedFathomServiceServer) testEmbeddedByValue()                       {}

// UnsafeFathomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FathomServiceServer will
// result in compilation errors.
type UnsafeFathomServiceServer interface {
	mustEmbedUnimplementedFathomServiceServer()
}

func RegisterFathomServiceServer(s grpc.ServiceRegistrar, srv FathomServiceServer) {
	// If the following call panics, it indicates UnimplementedFathomServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FathomService_ServiceDesc, srv)
}

func _FathomService_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FathomServiceServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FathomService_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FathomServiceServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FathomService_AssertFact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssertFactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FathomServiceServer).AssertFact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FathomService_AssertFact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FathomServiceServer).AssertFact(ctx, req.(*AssertFactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FathomService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FathomServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FathomService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FathomServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FathomService_Retract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FathomServiceServer).Retract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FathomService_Retract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FathomServiceServer).Retract(ctx, req.(*RetractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FathomService_SubscribeChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FathomServiceServer).SubscribeChanges(m, &grpc.GenericServerStream[SubscribeRequest, FactChange]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FathomService_SubscribeChangesServer = grpc.ServerStreamingServer[FactChange]

func _FathomService_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FathomServiceServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FathomService_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FathomServiceServer).Reload(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FathomService_ServiceDesc is the grpc.ServiceDesc for FathomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FathomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fathom.v1.FathomService",
	HandlerType: (*FathomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _FathomService_Evaluate_Handler,
		},
		{
			MethodName: "AssertFact",
			Handler:    _FathomService_AssertFact_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _FathomService_Query_Handler,
		},
		{
			MethodName: "Retract",
			Handler:    _FathomService_Retract_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _FathomService_Reload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeChanges",
			Handler:       _FathomService_SubscribeChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fathom.proto",
}
