// Fathom gRPC service definition.
//
// Provides remote access to the Fathom deterministic reasoning engine
// for evaluating policy rules, managing working memory, and streaming
// fact changes.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: fathom.proto

package fathomv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeType int32

const (
	ChangeType_CHANGE_TYPE_UNSPECIFIED ChangeType = 0
	ChangeType_ASSERT                  ChangeType = 1
	ChangeType_RETRACT                 ChangeType = 2
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "CHANGE_TYPE_UNSPECIFIED",
		1: "ASSERT",
		2: "RETRACT",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_TYPE_UNSPECIFIED": 0,
		"ASSERT":                  1,
		"RETRACT":                 2,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_fathom_proto_enumTypes[0].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_fathom_proto_enumTypes[0]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_fathom_proto_rawDescGZIP(), []int{0}
}

type FactInput struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Template string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	// JSON-encoded slot data (e.g. {"tool_name": "bash", "agent_id": "a1"}).
	DataJson      string `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactInput) Reset() {
	*x = FactInput{}
	mi := &file_fathom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactInput) ProtoMessage() {}

func (x *FactInput) ProtoReflect() protoreflect.Message {
	mi := &file_fathom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactInput.ProtoReflect.Descriptor instead.
func (*FactInput) Descriptor() ([]byte, []int) {
	return file_fathom_proto_rawDescGZIP(), []int{0}
}

func (x *FactInput) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *FactInput) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type EvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Ruleset       string                 `protobuf:"bytes,2,opt,name=ruleset,proto3" json:"ruleset,omitempty"`
	Facts         []*FactInput           `protobuf:"bytes,3,rep,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_fathom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fathom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_fathom_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EvaluateRequest) GetRuleset() string {
	if x != nil {
		return x.Ruleset
	}
	return ""
}

func (x *EvaluateRequest) GetFacts() []*FactInput {
	if x != nil {
		return x.Facts
	}
	return nil
}

type EvaluateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      string                 `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RuleTrace     []string               `protobuf:"bytes,3,rep,name=rule_trace,json=ruleTrace,proto3" json:"rule_trace,omitempty"`
	ModuleTrace   []string               `protobuf:"bytes,4,rep,name=module_trace,json=moduleTrace,proto3" json:"module_trace,omitempty"`
	DurationUs    int64                  `protobuf:"varint,5,opt,name=duration_us,json=durationUs,proto3" json:"duration_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_fathom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fathom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_fathom_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluateResponse) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *EvaluateResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EvaluateResponse) GetRuleTrace() []string {
	if x != nil {
		return x.RuleTrace
	}
	return nil
}

func (x *EvaluateResponse) GetModuleTrace() []string {
	if x != nil {
		return x.ModuleTrace
	}
	return nil
}

func (x *EvaluateResponse) GetDurationUs() int64 {
	if x != nil {
		return x.DurationUs
	}
	return 0
}

type AssertFactRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Template  string                 `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	// JSON-encoded slot data.
	DataJson      string `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssertFactRequest) Reset() {
	*x = AssertFactRequest{}
	mi := &file_fathom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertFactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertFactRequest) ProtoMessage() {}

func (x *AssertFactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fathom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertFactRequest.ProtoReflect.Descriptor instead.
func (*AssertFactRequest) Descriptor() ([]byte, []int) {
	return file_fathom_proto_rawDescGZIP(), []int{3}
}

func (x *AssertFactRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AssertFactRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *AssertFactRequest) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type AssertFactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssertFactResponse) Reset() {
	*x = AssertFactResponse{}
	mi := &file_fathom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertFactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertFactResponse) ProtoMessage() {}

func (x *AssertFactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fathom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertFactResponse.ProtoReflect.Descriptor instead.
func (*AssertFactResponse) Descriptor() ([]byte, []int) {
	return file_fathom_proto_rawDescGZIP(), []int{4}
}

func (x *AssertFactResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type QueryRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Template  string                 `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	// Optional JSON-encoded filter (e.g. {"agent_id": "a1"}).
	FilterJson    string `protobuf:"bytes,3,opt,name=filter_json,json=filterJson,proto3" json:"filter_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_fathom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fathom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_fathom_proto_rawDescGZIP(), []int{5}
}

func (x *QueryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *QueryRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *QueryRequest) GetFilterJson() string {
	if x != nil {
		return x.FilterJson
	}
	return ""
}

type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each entry is a JSON-encoded dict representing one fact.
	FactsJson     []string `protobuf:"bytes,1,rep,name=facts_json,json=factsJson,proto3" json:"facts_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_fathom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fathom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_fathom_proto_rawDescGZIP(), []int{6}
}

func (x *QueryResponse) GetFactsJson() []string {
	if x != nil {
		return x.FactsJson
	}
	return nil
}

type RetractRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Template  string                 `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	// Optional JSON-encoded filter.
	FilterJson    string `protobuf:"bytes,3,opt,name=filter_json,json=filterJson,proto3" json:"filter_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetractRequest) Reset() {
	*x = RetractRequest{}
	mi := &file_fathom_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractRequest) ProtoMessage() {}

func (x *RetractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fathom_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractRequest.ProtoReflect.Descriptor instead.
func (*RetractRequest) Descriptor() ([]byte, []int) {
	return file_fathom_proto_rawDescGZIP(), []int{7}
}

func (x *RetractRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RetractRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *RetractRequest) GetFilterJson() string {
	if x != nil {
		return x.FilterJson
	}
	return ""
}

type RetractResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RetractedCount int32                  `protobuf:"varint,1,opt,name=retracted_count,json=retractedCount,proto3" json:"retracted_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RetractResponse) Reset() {
	*x = RetractResponse{}
	mi := &file_fathom_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractResponse) ProtoMessage() {}

func (x *RetractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fathom_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractResponse.ProtoReflect.Descriptor instead.
func (*RetractResponse) Descriptor() ([]byte, []int) {
	return file_fathom_proto_rawDescGZIP(), []int{8}
}

func (x *RetractResponse) GetRetractedCount() int32 {
	if x != nil {
		return x.RetractedCount
	}
	return 0
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_fathom_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fathom_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_fathom_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type FactChange struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ChangeType ChangeType             `protobuf:"varint,1,opt,name=change_type,json=changeType,proto3,enum=fathom.v1.ChangeType" json:"change_type,omitempty"`
	Template   string                 `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	// JSON-encoded slot data of the changed fact.
	DataJson      string `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactChange) Reset() {
	*x = FactChange{}
	mi := &file_fathom_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactChange) ProtoMessage() {}

func (x *FactChange) ProtoReflect() protoreflect.Message {
	mi := &file_fathom_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactChange.ProtoReflect.Descriptor instead.
func (*FactChange) Descriptor() ([]byte, []int) {
	return file_fathom_proto_rawDescGZIP(), []int{10}
}

func (x *FactChange) GetChangeType() ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ChangeType_CHANGE_TYPE_UNSPECIFIED
}

func (x *FactChange) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *FactChange) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type ReloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*ReloadRequest_RulesetPath
	//	*ReloadRequest_RulesetYaml
	Source        isReloadRequest_Source `protobuf_oneof:"source"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	mi := &file_fathom_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fathom_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_fathom_proto_rawDescGZIP(), []int{11}
}

func (x *ReloadRequest) GetSource() isReloadRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ReloadRequest) GetRulesetPath() string {
	if x != nil {
		if x, ok := x.Source.(*ReloadRequest_RulesetPath); ok {
			return x.RulesetPath
		}
	}
	return ""
}

func (x *ReloadRequest) GetRulesetYaml() string {
	if x != nil {
		if x, ok := x.Source.(*ReloadRequest_RulesetYaml); ok {
			return x.RulesetYaml
		}
	}
	return ""
}

func (x *ReloadRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type isReloadRequest_Source interface {
	isReloadRequest_Source()
}

type ReloadRequest_RulesetPath struct {
	RulesetPath string `protobuf:"bytes,1,opt,name=ruleset_path,json=rulesetPath,proto3,oneof"`
}

type ReloadRequest_RulesetYaml struct {
	RulesetYaml string `protobuf:"bytes,2,opt,name=ruleset_yaml,json=rulesetYaml,proto3,oneof"`
}

func (*ReloadRequest_RulesetPath) isReloadRequest_Source() {}

func (*ReloadRequest_RulesetYaml) isReloadRequest_Source() {}

type ReloadResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RulesetHashBefore string                 `protobuf:"bytes,1,opt,name=ruleset_hash_before,json=rulesetHashBefore,proto3" json:"ruleset_hash_before,omitempty"`
	RulesetHashAfter  string                 `protobuf:"bytes,2,opt,name=ruleset_hash_after,json=rulesetHashAfter,proto3" json:"ruleset_hash_after,omitempty"`
	AttestationToken  string                 `protobuf:"bytes,3,opt,name=attestation_token,json=attestationToken,proto3" json:"attestation_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReloadResponse) Reset() {
	*x = ReloadResponse{}
	mi := &file_fathom_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadResponse) ProtoMessage() {}

func (x *ReloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fathom_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadResponse.ProtoReflect.Descriptor instead.
func (*ReloadResponse) Descriptor() ([]byte, []int) {
	return file_fathom_proto_rawDescGZIP(), []int{12}
}

func (x *ReloadResponse) GetRulesetHashBefore() string {
	if x != nil {
		return x.RulesetHashBefore
	}
	return ""
}

func (x *ReloadResponse) GetRulesetHashAfter() string {
	if x != nil {
		return x.RulesetHashAfter
	}
	return ""
}

func (x *ReloadResponse) GetAttestationToken() string {
	if x != nil {
		return x.AttestationToken
	}
	return ""
}

var File_fathom_proto protoreflect.FileDescriptor

const file_fathom_proto_rawDesc = "" +
	"\n" +
	"\ffathom.proto\x12\tfathom.v1\"D\n" +
	"\tFactInput\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\tR\bdataJson\"v\n" +
	"\x0fEvaluateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\aruleset\x18\x02 \x01(\tR\aruleset\x12*\n" +
	"\x05facts\x18\x03 \x03(\v2\x14.fathom.v1.FactInputR\x05facts\"\xa9\x01\n" +
	"\x10EvaluateResponse\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\tR\bdecision\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"rule_trace\x18\x03 \x03(\tR\truleTrace\x12!\n" +
	"\fmodule_trace\x18\x04 \x03(\tR\vmoduleTrace\x12\x1f\n" +
	"\vduration_us\x18\x05 \x01(\x03R\n" +
	"durationUs\"k\n" +
	"\x11AssertFactRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\btemplate\x18\x02 \x01(\tR\btemplate\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\tR\bdataJson\".\n" +
	"\x12AssertFactResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"j\n" +
	"\fQueryRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\btemplate\x18\x02 \x01(\tR\btemplate\x12\x1f\n" +
	"\vfilter_json\x18\x03 \x01(\tR\n" +
	"filterJson\".\n" +
	"\rQueryResponse\x12\x1d\n" +
	"\n" +
	"facts_json\x18\x01 \x03(\tR\tfactsJson\"l\n" +
	"\x0eRetractRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\btemplate\x18\x02 \x01(\tR\btemplate\x12\x1f\n" +
	"\vfilter_json\x18\x03 \x01(\tR\n" +
	"filterJson\":\n" +
	"\x0fRetractResponse\x12'\n" +
	"\x0fretracted_count\x18\x01 \x01(\x05R\x0eretractedCount\"1\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"}\n" +
	"\n" +
	"FactChange\x126\n" +
	"\vchange_type\x18\x01 \x01(\x0e2\x15.fathom.v1.ChangeTypeR\n" +
	"changeType\x12\x1a\n" +
	"\btemplate\x18\x02 \x01(\tR\btemplate\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\tR\bdataJson\"\x81\x01\n" +
	"\rReloadRequest\x12#\n" +
	"\fruleset_path\x18\x01 \x01(\tH\x00R\vrulesetPath\x12#\n" +
	"\fruleset_yaml\x18\x02 \x01(\tH\x00R\vrulesetYaml\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignatureB\b\n" +
	"\x06source\"\x9b\x01\n" +
	"\x0eReloadResponse\x12.\n" +
	"\x13ruleset_hash_before\x18\x01 \x01(\tR\x11rulesetHashBefore\x12,\n" +
	"\x12ruleset_hash_after\x18\x02 \x01(\tR\x10rulesetHashAfter\x12+\n" +
	"\x11attestation_token\x18\x03 \x01(\tR\x10attestationToken*B\n" +
	"\n" +
	"ChangeType\x12\x1b\n" +
	"\x17CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ASSERT\x10\x01\x12\v\n" +
	"\aRETRACT\x10\x022\xa6\x03\n" +
	"\rFathomService\x12C\n" +
	"\bEvaluate\x12\x1a.fathom.v1.EvaluateRequest\x1a\x1b.fathom.v1.EvaluateResponse\x12I\n" +
	"\n" +
	"AssertFact\x12\x1c.fathom.v1.AssertFactRequest\x1a\x1d.fathom.v1.AssertFactResponse\x12:\n" +
	"\x05Query\x12\x17.fathom.v1.QueryRequest\x1a\x18.fathom.v1.QueryResponse\x12@\n" +
	"\aRetract\x12\x19.fathom.v1.RetractRequest\x1a\x1a.fathom.v1.RetractResponse\x12H\n" +
	"\x10SubscribeChanges\x12\x1b.fathom.v1.SubscribeRequest\x1a\x15.fathom.v1.FactChange0\x01\x12=\n" +
	"\x06Reload\x12\x18.fathom.v1.ReloadRequest\x1a\x19.fathom.v1.ReloadResponseB>\n" +
	"\rcom.fathom.v1Z-github.com/KrakenNet/fathom-go/proto;fathomv1b\x06proto3"

var (
	file_fathom_proto_rawDescOnce sync.Once
	file_fathom_proto_rawDescData []byte
)

func file_fathom_proto_rawDescGZIP() []byte {
	file_fathom_proto_rawDescOnce.Do(func() {
		file_fathom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fathom_proto_rawDesc), len(file_fathom_proto_rawDesc)))
	})
	return file_fathom_proto_rawDescData
}

var file_fathom_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fathom_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_fathom_proto_goTypes = []any{
	(ChangeType)(0),            // 0: fathom.v1.ChangeType
	(*FactInput)(nil),          // 1: fathom.v1.FactInput
	(*EvaluateRequest)(nil),    // 2: fathom.v1.EvaluateRequest
	(*EvaluateResponse)(nil),   // 3: fathom.v1.EvaluateResponse
	(*AssertFactRequest)(nil),  // 4: fathom.v1.AssertFactRequest
	(*AssertFactResponse)(nil), // 5: fathom.v1.AssertFactResponse
	(*QueryRequest)(nil),       // 6: fathom.v1.QueryRequest
	(*QueryResponse)(nil),      // 7: fathom.v1.QueryResponse
	(*RetractRequest)(nil),     // 8: fathom.v1.RetractRequest
	(*RetractResponse)(nil),    // 9: fathom.v1.RetractResponse
	(*SubscribeRequest)(nil),   // 10: fathom.v1.SubscribeRequest
	(*FactChange)(nil),         // 11: fathom.v1.FactChange
	(*ReloadRequest)(nil),      // 12: fathom.v1.ReloadRequest
	(*ReloadResponse)(nil),     // 13: fathom.v1.ReloadResponse
}
var file_fathom_proto_depIdxs = []int32{
	1,  // 0: fathom.v1.EvaluateRequest.facts:type_name -> fathom.v1.FactInput
	0,  // 1: fathom.v1.FactChange.change_type:type_name -> fathom.v1.ChangeType
	2,  // 2: fathom.v1.FathomService.Evaluate:input_type -> fathom.v1.EvaluateRequest
	4,  // 3: fathom.v1.FathomService.AssertFact:input_type -> fathom.v1.AssertFactRequest
	6,  // 4: fathom.v1.FathomService.Query:input_type -> fathom.v1.QueryRequest
	8,  // 5: fathom.v1.FathomService.Retract:input_type -> fathom.v1.RetractRequest
	10, // 6: fathom.v1.FathomService.SubscribeChanges:input_type -> fathom.v1.SubscribeRequest
	12, // 7: fathom.v1.FathomService.Reload:input_type -> fathom.v1.ReloadRequest
	3,  // 8: fathom.v1.FathomService.Evaluate:output_type -> fathom.v1.EvaluateResponse
	5,  // 9: fathom.v1.FathomService.AssertFact:output_type -> fathom.v1.AssertFactResponse
	7,  // 10: fathom.v1.FathomService.Query:output_type -> fathom.v1.QueryResponse
	9,  // 11: fathom.v1.FathomService.Retract:output_type -> fathom.v1.RetractResponse
	11, // 12: fathom.v1.FathomService.SubscribeChanges:output_type -> fathom.v1.FactChange
	13, // 13: fathom.v1.FathomService.Reload:output_type -> fathom.v1.ReloadResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_fathom_proto_init() }
func file_fathom_proto_init() {
	if File_fathom_proto != nil {
		return
	}
	file_fathom_proto_msgTypes[11].OneofWrappers = []any{
		(*ReloadRequest_RulesetPath)(nil),
		(*ReloadRequest_RulesetYaml)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fathom_proto_rawDesc), len(file_fathom_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fathom_proto_goTypes,
		DependencyIndexes: file_fathom_proto_depIdxs,
		EnumInfos:         file_fathom_proto_enumTypes,
		MessageInfos:      file_fathom_proto_msgTypes,
	}.Build()
	File_fathom_proto = out.File
	file_fathom_proto_goTypes = nil
	file_fathom_proto_depIdxs = nil
}
